site_name: merise_dot
theme:
  name: mkdocs
  color_mode: dark

nav:
  - Home: index.md
  - Getting Started: quickstart.md
  - Graphs:
    - MCD: mcd.md
    - MLD: mld.md
    - SQL: 
      - conversion: sql.md
      - semantics:
        - tables: sql_tables.md
      - constraints:
        - foreign keys: foreignkeys.md
        - unique constraint: unique.md
